### ISSUE TITLE
Missing metadata tags in v3.0/3.1

### ISSUE THREAD

**Issue by retromoustache** [moonshinegloss/stable-diffusion-discord-prompts#10]
Comparing both 2.7 and 3.1 versions of the script, the model hash and model name are not present in the metadata output. Size of the image seems to appear in some images and not others.

**2.7 version output:**
![image](https://user-images.githubusercontent.com/46168323/219804798-c9cebc79-4eb6-4f3d-bb02-88f5f1bc7eab.png)

**3.1 version output:**
![image](https://user-images.githubusercontent.com/46168323/219804724-b02f49ff-d9c4-4ffb-8193-46a2dd39b713.png)

Link to the [png](https://discord.com/channels/1010980909568245801/1029835515001831494/1074955659881222205) in question.

**Comment by moonshinegloss** [comment]
great catch thanks!
