### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by kwikmn** [moonshinegloss/stable-diffusion-discord-prompts#13]
I assume it's a change on Discord's end, because the plugin appears to have stopped working about two weeks ago. Just thought you should know.

**Comment by moonshinegloss** [comment]
quickly skimming the issue; it seems the prompts fetching still works, it's the injecting the button that's broken, I'll take a look once I have more time

**Comment by moonshinegloss** [comment]
![image](https://github.com/moonshinegloss/stable-diffusion-discord-prompts/assets/118488816/ab0ead96-bb7e-408e-8083-9b091e2146a0)

naive approach seems to have worked, going to push it up soon.

**Comment by moonshinegloss** [comment]
done
